version: "3"

services:
  db:
    image: postgres:10.1
    container_name: flyinspect-db
    restart: always
    environment:
      POSTGRES_PASSWORD: fly@inspect
      POSTGRES_USER: flyinspect
    # user: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db:/db
    ports:
      - '5432:5432'

  # api:
  #   build: ./docker/php
  #   working_dir: /opt/fly-inpect/api
  #   volumes:
  #     - ./api:/opt/fly-inpect/api
  #     - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  #   ports:
  #     - '9000:9000'
  #   depends_on:
  #     - db

  api:
    build: ./api_python
    container_name: flyinspect-api
    working_dir: /opt/fly-inpect/api
    user: nobody
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: flyinspect
      DB_USER: flyinspect
      DB_PASSWORD: fly@inspect
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 'True'
    volumes:
      - ./api_python:/opt/fly-inpect/api
    ports:
      - '8000:8000'
      - '3500:3500'
    command: ./manage.py runserver 0.0.0.0:8000 --noreload
    depends_on:
      - db

  app:
    image: node:9.2
    container_name: flyinspect-app
    user: node
    working_dir: /opt/fly-inpect/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/opt/fly-inpect/app
    ports:
      - '3000:3000'
    command: sh -c "yarn && yarn start"
    depends_on:
      - api

  web:
    image: nginx:1.13
    container_name: flyinspect-web
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - api
      - app
