# Generated by Django 2.0 on 2017-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyinspect_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fld_code', models.CharField(db_column='code', max_length=30)),
                ('fld_description', models.CharField(blank=True, db_column='description', max_length=80, null=True)),
                ('fld_type', models.CharField(blank=True, db_column='type', max_length=4, null=True)),
                ('fld_rtype', models.CharField(blank=True, db_column='rtype', max_length=4, null=True)),
                ('fld_date', models.DateField(blank=True, db_column='date', null=True)),
                ('fld_status', models.CharField(blank=True, db_column='status', max_length=4, null=True)),
                ('fld_rstatus', models.CharField(blank=True, db_column='rstatus', max_length=4, null=True)),
            ],
            options={
                'db_table': 'tbl_entity',
            },
        ),
    ]
