# Generated by Django 2.0 on 2017-12-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyinspect_api', '0002_entity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Event',
        ),
        migrations.AlterModelTable(
            name='event',
            table='tbl_event',
        ),
    ]
